name: ReneCV
author: Rene

defaults:
  -
    scope:
      path: ""
    values:
      layout: "polymer"

markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighting: rouge

highlighter: rouge
