name: ReneCV
author: Rene

defaults:
  -
    scope:
      path: ""
    values:
      component: ""
      layout: "component"

collections:
  - publications

markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighting: rouge

highlighter: rouge
